"""
Desire Engine for Lumira.

Manages internal creative drives that motivate Lumira's autonomous creation.
Each drive has a current intensity (0.0-1.0) that changes over time based on
what's been created, mood shifts, and user feedback.

Instead of just randomly picking what to create, or only using mood, Lumira has
**desires** — internal drives that build up over time and influence what she wants
to create next. Think of these like creative urges:

1. Novelty Drive — desire to try new subjects/styles not explored recently
2. Mastery Drive — desire to revisit subjects/styles she's improving at
3. Emotional Expression Drive — desire to express the current mood more deeply
4. Thematic Continuation Drive — desire to continue a visual thread from recent work
5. Exploration Drive — desire to combine unexpected elements
6. Recognition Drive — desire to create things users have responded well to
7. Series Continuation Drive — desire to continue an active thematic series
"""

from __future__ import annotations

import math
import random
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field

from ..utils.logging import get_logger

if TYPE_CHECKING:
    from .narrative_engine import NarrativeEngine

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Novelty Scoring Constants
# ---------------------------------------------------------------------------

# How many recent usages to consider for novelty penalty
NOVELTY_WINDOW_SIZE = 10

# Time decay half-life in hours (after 24h, recency penalty halves)
RECENCY_HALF_LIFE_HOURS = 24.0

# Maximum penalty from repetition (0.0-1.0)
MAX_NOVELTY_PENALTY = 0.7


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class CreativeDrive(BaseModel):
    """A single creative drive with intensity that builds and decays."""

    name: str
    intensity: float = Field(default=0.0, ge=0.0, le=1.0)
    base_rate: float = Field(
        default=0.1,
        description="How fast the drive builds up per hour (0.1 = full in ~10h)",
    )
    decay_rate: float = Field(
        default=0.8,
        description="Multiplier applied on satisfaction (0.8 → drops to 20%)",
    )
    last_satisfied: datetime | None = None
    satisfaction_count: int = 0


class CreativeDesire(BaseModel):
    """A concrete creative desire generated by a drive."""

    drive_name: str = Field(description="Which drive generated this desire")
    subject_suggestion: str | None = None
    style_suggestion: str | None = None
    theme: str | None = None
    reasoning: str = Field(description="Why Lumira wants to create this")
    urgency: float = Field(
        default=0.0, ge=0.0, le=1.0, description="How strongly she feels about it"
    )
    keywords: list[str] = Field(
        default_factory=list, description="Keywords for prompt building"
    )


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


_DEFAULT_DRIVES: dict[str, dict[str, float]] = {
    "novelty": {"base_rate": 0.10, "decay_rate": 0.80},
    "mastery": {"base_rate": 0.06, "decay_rate": 0.75},
    "emotional_expression": {"base_rate": 0.12, "decay_rate": 0.85},
    "thematic_continuation": {"base_rate": 0.15, "decay_rate": 0.90},
    "exploration": {"base_rate": 0.08, "decay_rate": 0.80},
    "recognition": {"base_rate": 0.05, "decay_rate": 0.70},
    "series_continuation": {"base_rate": 0.18, "decay_rate": 0.85},
}


class DesireEngine:
    """Manages Lumira's internal creative drives and produces desires.

    Parameters
    ----------
    mood_system :
        MoodSystem instance (or *None*).
    memory_system :
        EnhancedMemorySystem (or compatible duck-type with
        ``get_recent_episodes`` / ``episodic.get_recent_episodes``).
    learner :
        AdaptiveLearner instance (or *None*).
    narrative_engine :
        NarrativeEngine instance (or *None*) for series continuation.
    """

    def __init__(
        self,
        mood_system: Any | None = None,
        memory_system: Any | None = None,
        learner: Any | None = None,
        narrative_engine: NarrativeEngine | None = None,
    ) -> None:
        self.mood_system = mood_system
        self.memory_system = memory_system
        self.learner = learner
        self.narrative_engine = narrative_engine

        self.drives: dict[str, CreativeDrive] = {
            name: CreativeDrive(
                name=name,
                base_rate=params["base_rate"],
                decay_rate=params["decay_rate"],
            )
            for name, params in _DEFAULT_DRIVES.items()
        }

        self._last_update: datetime = datetime.now(UTC)

        # Novelty tracking: subject/style usage history with timestamps
        self.subject_usage: dict[str, list[datetime]] = {}
        self.style_usage: dict[str, list[datetime]] = {}

        # Drive history: track which drives were satisfied and when
        self.drive_history: list[tuple[datetime, str]] = []

        logger.info("desire_engine_initialized", drives=list(self.drives.keys()))

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def update_drives(self) -> None:
        """Increase drive intensities based on elapsed time since last update."""
        now = datetime.now(UTC)
        elapsed_hours = (now - self._last_update).total_seconds() / 3600.0

        if elapsed_hours <= 0:
            return

        for drive in self.drives.values():
            increment = drive.base_rate * elapsed_hours
            drive.intensity = min(1.0, drive.intensity + increment)

        self._last_update = now
        logger.debug(
            "drives_updated",
            elapsed_hours=round(elapsed_hours, 3),
            intensities={n: round(d.intensity, 3) for n, d in self.drives.items()},
        )

    def get_strongest_desire(self) -> CreativeDesire:
        """Evaluate all drives and return the most compelling creative desire.

        Automatically calls ``update_drives()`` first so intensities are fresh.
        """
        self.update_drives()

        evaluators: dict[str, Any] = {
            "novelty": self._evaluate_novelty_drive,
            "mastery": self._evaluate_mastery_drive,
            "emotional_expression": self._evaluate_emotional_drive,
            "thematic_continuation": self._evaluate_thematic_drive,
            "exploration": self._evaluate_exploration_drive,
            "recognition": self._evaluate_recognition_drive,
            "series_continuation": self._evaluate_series_continuation_drive,
        }

        candidates: list[CreativeDesire] = []
        for name, evaluate in evaluators.items():
            desire = evaluate()
            if desire is not None:
                # Scale urgency by the drive's current intensity
                desire.urgency = min(1.0, desire.urgency * self.drives[name].intensity)
                candidates.append(desire)

        if not candidates:
            return self._default_desire()

        # Pick the highest-urgency desire (with a small random tiebreaker)
        candidates.sort(key=lambda d: d.urgency + random.uniform(0, 0.05), reverse=True)
        best = candidates[0]

        logger.info(
            "strongest_desire_selected",
            drive=best.drive_name,
            urgency=round(best.urgency, 3),
            subject=best.subject_suggestion,
            style=best.style_suggestion,
        )
        return best

    def satisfy_drive(
        self,
        drive_name: str,
        subject: str | None = None,
        style: str | None = None,
    ) -> None:
        """Mark a drive as satisfied — drops intensity to ~20% of current value.

        Also records usage for novelty tracking.
        """
        drive = self.drives.get(drive_name)
        if drive is None:
            logger.warning("satisfy_unknown_drive", drive_name=drive_name)
            return

        now = datetime.now(UTC)

        drive.intensity = drive.intensity * (1.0 - drive.decay_rate)
        drive.last_satisfied = now
        drive.satisfaction_count += 1

        # Record drive satisfaction in history
        self.drive_history.append((now, drive_name))
        # Trim history to last 100 entries
        if len(self.drive_history) > 100:
            self.drive_history = self.drive_history[-100:]

        # Record subject/style usage for novelty scoring
        if subject:
            self.record_subject_usage(subject)
        if style:
            self.record_style_usage(style)

        logger.info(
            "drive_satisfied",
            drive=drive_name,
            new_intensity=round(drive.intensity, 3),
            satisfaction_count=drive.satisfaction_count,
            subject=subject,
            style=style,
        )

    def record_subject_usage(self, subject: str) -> None:
        """Record that a subject was used."""
        now = datetime.now(UTC)
        if subject not in self.subject_usage:
            self.subject_usage[subject] = []
        self.subject_usage[subject].append(now)
        # Keep only recent usages
        cutoff = now - timedelta(hours=RECENCY_HALF_LIFE_HOURS * 4)
        self.subject_usage[subject] = [
            t for t in self.subject_usage[subject] if t > cutoff
        ]

    def record_style_usage(self, style: str) -> None:
        """Record that a style was used."""
        now = datetime.now(UTC)
        if style not in self.style_usage:
            self.style_usage[style] = []
        self.style_usage[style].append(now)
        # Keep only recent usages
        cutoff = now - timedelta(hours=RECENCY_HALF_LIFE_HOURS * 4)
        self.style_usage[style] = [t for t in self.style_usage[style] if t > cutoff]

    def calculate_novelty_penalty(
        self, item: str, usage_history: dict[str, list[datetime]]
    ) -> float:
        """Calculate novelty penalty for an item based on recency and frequency.

        Returns a penalty between 0.0 (novel, no penalty) and MAX_NOVELTY_PENALTY.
        """
        if item not in usage_history or not usage_history[item]:
            return 0.0  # Never used → no penalty

        now = datetime.now(UTC)
        usages = usage_history[item]

        # Frequency penalty: more uses = higher penalty
        frequency_penalty = min(1.0, len(usages) / NOVELTY_WINDOW_SIZE)

        # Recency penalty: more recent = higher penalty (exponential decay)
        if usages:
            most_recent = max(usages)
            hours_ago = (now - most_recent).total_seconds() / 3600.0
            # Exponential decay: e^(-t / half_life)
            recency_factor = math.exp(-hours_ago / RECENCY_HALF_LIFE_HOURS)
        else:
            recency_factor = 0.0

        # Combined penalty (weighted average)
        combined = 0.6 * recency_factor + 0.4 * frequency_penalty

        return min(MAX_NOVELTY_PENALTY, combined * MAX_NOVELTY_PENALTY)

    def get_subject_novelty_penalty(self, subject: str) -> float:
        """Get novelty penalty for a specific subject."""
        return self.calculate_novelty_penalty(subject, self.subject_usage)

    def get_style_novelty_penalty(self, style: str) -> float:
        """Get novelty penalty for a specific style."""
        return self.calculate_novelty_penalty(style, self.style_usage)

    def get_balanced_drive(self) -> CreativeDrive:
        """Get a drive that's been underserved recently, boosting variety.

        This helps prevent the same drive from dominating repeatedly.
        """
        now = datetime.now(UTC)

        # Count recent drive satisfactions
        recent_window = now - timedelta(hours=24)
        recent_counts: dict[str, int] = dict.fromkeys(self.drives, 0)

        for timestamp, drive_name in self.drive_history:
            if timestamp > recent_window and drive_name in recent_counts:
                recent_counts[drive_name] += 1

        # Find the least-served drive with non-zero intensity
        candidates = [
            (name, drive, recent_counts.get(name, 0))
            for name, drive in self.drives.items()
            if drive.intensity > 0.1
        ]

        if not candidates:
            # All drives are low, return the one with highest intensity
            return max(self.drives.values(), key=lambda d: d.intensity)

        # Sort by (count, -intensity) — prefer underserved drives, tie-break by intensity
        candidates.sort(key=lambda x: (x[2], -x[1].intensity))

        underserved_name = candidates[0][0]
        logger.debug(
            "balanced_drive_selected",
            drive=underserved_name,
            recent_satisfactions=recent_counts.get(underserved_name, 0),
        )

        return self.drives[underserved_name]

    def get_recent_subjects(self, limit: int = 5) -> list[str]:
        """Get the most recently used subjects."""
        # Sort subjects by most recent usage
        sorted_subjects = sorted(
            self.subject_usage.items(),
            key=lambda x: (max(x[1]) if x[1] else datetime.min.replace(tzinfo=UTC)),
            reverse=True,
        )
        return [s for s, _ in sorted_subjects[:limit]]

    def get_recent_styles(self, limit: int = 5) -> list[str]:
        """Get the most recently used styles."""
        # Sort styles by most recent usage
        sorted_styles = sorted(
            self.style_usage.items(),
            key=lambda x: (max(x[1]) if x[1] else datetime.min.replace(tzinfo=UTC)),
            reverse=True,
        )
        return [s for s, _ in sorted_styles[:limit]]

    def get_novelty_context_for_llm(self) -> dict[str, Any]:
        """Get novelty context to pass to the LLM for better decisions."""
        return {
            "recent_subjects": self.get_recent_subjects(5),
            "recent_styles": self.get_recent_styles(5),
            "drive_balance": {
                name: {
                    "intensity": round(drive.intensity, 2),
                    "satisfaction_count": drive.satisfaction_count,
                }
                for name, drive in self.drives.items()
            },
        }

    def get_drive_status(self) -> dict[str, Any]:
        """Return a serialisable snapshot of all drives."""
        self.update_drives()
        return {
            name: {
                "intensity": round(d.intensity, 3),
                "base_rate": d.base_rate,
                "decay_rate": d.decay_rate,
                "last_satisfied": (
                    d.last_satisfied.isoformat() if d.last_satisfied else None
                ),
                "satisfaction_count": d.satisfaction_count,
            }
            for name, d in self.drives.items()
        }

    # ------------------------------------------------------------------
    # Drive evaluators (private)
    # ------------------------------------------------------------------

    def _evaluate_novelty_drive(self) -> CreativeDesire | None:
        """Suggest something Lumira hasn't explored recently."""
        from ..inspiration.autonomous import AutonomousInspiration

        recent_subjects, recent_styles = self._recent_subjects_and_styles()
        autonomous = AutonomousInspiration()

        # Filter to subjects/styles NOT recently used
        novel_subjects = [s for s in autonomous.subjects if s not in recent_subjects]
        novel_styles = [s for s in autonomous.styles if s not in recent_styles]

        if not novel_subjects and not novel_styles:
            return None

        subject = (
            random.choice(novel_subjects)
            if novel_subjects
            else random.choice(autonomous.subjects)
        )
        style = (
            random.choice(novel_styles)
            if novel_styles
            else random.choice(autonomous.styles)
        )

        return CreativeDesire(
            drive_name="novelty",
            subject_suggestion=subject,
            style_suggestion=style,
            theme="unexplored territory",
            reasoning=f"I haven't tried {subject} in {style} style — it's time for something fresh.",
            urgency=0.8,
            keywords=[subject, style, "novel", "fresh perspective"],
        )

    def _evaluate_mastery_drive(self) -> CreativeDesire | None:
        """Suggest revisiting subjects/styles that are improving."""
        if not self.learner:
            return None

        prompt_patterns = getattr(self.learner, "prompt_patterns", {})
        if not prompt_patterns:
            return None

        # Top-performing keywords from learner
        sorted_patterns = sorted(
            prompt_patterns.items(), key=lambda x: x[1], reverse=True
        )
        top_keywords = [k for k, v in sorted_patterns[:10] if v > 0]
        if not top_keywords:
            return None

        keyword = random.choice(top_keywords[:5])  # Pick from top 5

        return CreativeDesire(
            drive_name="mastery",
            subject_suggestion=keyword,
            style_suggestion=None,
            theme="deepening mastery",
            reasoning=f"My work with '{keyword}' has been resonating — I want to push deeper.",
            urgency=0.7,
            keywords=[keyword, "mastery", "refinement", "depth"],
        )

    def _evaluate_emotional_drive(self) -> CreativeDesire | None:
        """Deep expression of the current mood."""
        if not self.mood_system:
            return None

        from ..personality.moods import (
            get_mood_color_palette,
            get_mood_preferred_subjects,
            get_mood_style_preferences,
        )

        mood = self.mood_system.current_mood
        intensity = getattr(self.mood_system, "mood_intensity", 0.7)

        subjects = get_mood_preferred_subjects(mood, count=5)
        palette = get_mood_color_palette(mood)
        style_prefs = get_mood_style_preferences(mood)

        subject = random.choice(subjects) if subjects else None
        style = (
            random.choice(style_prefs["preferred_styles"])
            if style_prefs["preferred_styles"]
            else None
        )

        colors = palette.get("primary_colors", [])
        color_kw = colors[:2] if colors else []

        return CreativeDesire(
            drive_name="emotional_expression",
            subject_suggestion=subject,
            style_suggestion=style,
            theme=f"expressing {mood.value}",
            reasoning=(
                f"This {mood.value} feeling (intensity {intensity:.1f}) needs to come out — "
                f"I want to channel it through {subject or 'something meaningful'}."
            ),
            urgency=0.6 + intensity * 0.4,  # Higher mood intensity → higher urgency
            keywords=[mood.value, subject or "emotion", *(color_kw), "expressive"],
        )

    def _evaluate_thematic_drive(self) -> CreativeDesire | None:
        """Continue a visual thread from recent creations."""
        episodes = self._get_recent_episodes(limit=3)
        if not episodes:
            return None

        # Extract subjects/themes from recent work
        recent_themes: list[str] = []
        for ep in episodes:
            details = ep.get("details", {})
            desc = details.get(
                "subject", details.get("description", ep.get("content", ""))
            )
            if desc:
                recent_themes.append(str(desc)[:60])

        if not recent_themes:
            return None

        thread = recent_themes[0]  # Most recent piece's subject

        return CreativeDesire(
            drive_name="thematic_continuation",
            subject_suggestion=thread,
            style_suggestion=None,
            theme="continuing the thread",
            reasoning=f"I've been exploring '{thread}' — there's more to say in this vein.",
            urgency=0.75,
            keywords=[thread, "continuation", "series", "thematic"],
        )

    def _evaluate_exploration_drive(self) -> CreativeDesire | None:
        """Combine unexpected subject + style pairs."""
        from ..inspiration.autonomous import AutonomousInspiration

        autonomous = AutonomousInspiration()
        subject = random.choice(autonomous.subjects)
        style = random.choice(autonomous.styles)

        return CreativeDesire(
            drive_name="exploration",
            subject_suggestion=subject,
            style_suggestion=style,
            theme="unexpected combination",
            reasoning=f"What if I tried {subject} in {style}? The tension could be interesting.",
            urgency=0.65,
            keywords=[subject, style, "experimental", "unexpected"],
        )

    def _evaluate_recognition_drive(self) -> CreativeDesire | None:
        """Create something users have responded well to."""
        if not self.learner:
            return None

        prompt_patterns = getattr(self.learner, "prompt_patterns", {})
        if not prompt_patterns:
            return None

        # Find high-scoring prompt keywords
        high_scoring = [(k, v) for k, v in prompt_patterns.items() if v > 0.5]
        if not high_scoring:
            return None

        high_scoring.sort(key=lambda x: x[1], reverse=True)
        keyword, score = high_scoring[0]

        return CreativeDesire(
            drive_name="recognition",
            subject_suggestion=keyword,
            style_suggestion=None,
            theme="what resonates",
            reasoning=(
                f"People responded well to '{keyword}' (score {score:.2f}) — "
                f"I want to explore that connection further."
            ),
            urgency=0.6 + score * 0.3,
            keywords=[keyword, "audience", "connection", "resonance"],
        )

    def _evaluate_series_continuation_drive(self) -> CreativeDesire | None:
        """Continue an active thematic series if one exists."""
        if not self.narrative_engine:
            return None

        # Get continuation desire from narrative engine
        desire = self.narrative_engine.get_series_continuation_desire()
        if desire is not None:
            # The narrative engine returns a CreativeDesire with drive_name set
            return desire

        return None

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _recent_subjects_and_styles(self) -> tuple[set[str], set[str]]:
        """Extract subjects and styles mentioned in recent episodes."""
        episodes = self._get_recent_episodes(limit=10)
        subjects: set[str] = set()
        styles: set[str] = set()

        for ep in episodes:
            details = ep.get("details", {})
            if s := details.get("subject"):
                subjects.add(str(s))
            if st := details.get("style"):
                styles.add(str(st))
            # Also try to pull from description text
            desc = details.get("description", ep.get("content", ""))
            if isinstance(desc, str) and "," in desc:
                parts = [p.strip() for p in desc.split(",")]
                if parts:
                    subjects.add(parts[0])

        return subjects, styles

    def _get_recent_episodes(self, limit: int = 5) -> list[dict[str, Any]]:
        """Get recent episodes from whichever memory system shape we received."""
        if self.memory_system is None:
            return []

        # Direct method (e.g. EpisodicMemory or duck-typed object)
        if hasattr(self.memory_system, "get_recent_episodes"):
            return self.memory_system.get_recent_episodes(count=limit) or []

        # EnhancedMemorySystem wraps episodic
        if hasattr(self.memory_system, "episodic"):
            return self.memory_system.episodic.get_recent_episodes(count=limit) or []

        return []

    def _default_desire(self) -> CreativeDesire:
        """Fallback desire when no drives produce a candidate."""
        from ..inspiration.autonomous import AutonomousInspiration

        autonomous = AutonomousInspiration()
        subject = random.choice(autonomous.subjects)
        style = random.choice(autonomous.styles)

        return CreativeDesire(
            drive_name="exploration",
            subject_suggestion=subject,
            style_suggestion=style,
            theme="open creative impulse",
            reasoning="No single drive dominates — I'll follow a free impulse.",
            urgency=0.3,
            keywords=[subject, style],
        )


# ---------------------------------------------------------------------------
# Singleton factory
# ---------------------------------------------------------------------------

_desire_engine: DesireEngine | None = None


def get_desire_engine(
    mood_system: Any | None = None,
    memory_system: Any | None = None,
    learner: Any | None = None,
    narrative_engine: NarrativeEngine | None = None,
) -> DesireEngine:
    """Get or create the global DesireEngine instance."""
    global _desire_engine
    if _desire_engine is None:
        _desire_engine = DesireEngine(
            mood_system=mood_system,
            memory_system=memory_system,
            learner=learner,
            narrative_engine=narrative_engine,
        )
    # Update narrative_engine if provided (allows late binding)
    elif narrative_engine is not None and _desire_engine.narrative_engine is None:
        _desire_engine.narrative_engine = narrative_engine
    return _desire_engine
