"""add_user_feedback_table

Revision ID: 3b4e3ea9e107
Revises: 0e34592e44db
Create Date: 2026-03-25 22:37:13.194553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4e3ea9e107'
down_revision: Union[str, None] = '0e34592e44db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('artwork_filename', sa.String(length=512), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['generated_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_artwork_filename'), ['artwork_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_artwork_id'), ['artwork_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_mood'), ['mood'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_mood'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_artwork_id'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_artwork_filename'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_action'))

    op.drop_table('user_feedback')
    # ### end Alembic commands ###
